version: '2'

services:

  web-angular:
    container_name: web-angular
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/myapp/frontend'
      - '/myapp/frontend/node_modules'
    links: 
      - backend
    ports:
      - '4201:4200'

  backend: #name of the second service
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" #specify ports forewarding
    container_name: back-container
    restart: always
    links:
      - database # link this service to the database service

  database: # name of the third service
    build: 
      context: ./database
      dockerfile: Dockerfile
    container_name: database-container
    restart: always